/**
 * The subcommands: `init`, `notes`, `changelog`, `check`, `explain`, `hook` and
 * `config`.
 *
 * **What they have in common is what the bare `cutver` does not:** none of them
 * cuts a version. Four are read-only or write one file, and their exit codes
 * answer to a hook or a publish job rather than to a person at a prompt. The
 * release sequence lives in `stage.ts` because it is the one path where an
 * early exit means a half-released repository.
 */
import { ADAPTER_FOR, ADAPTERS, applicableAdapters } from '../adapters'
import {
  compileRange,
  compileReleases,
  fullBodies,
  sectionOrCompile,
} from '../changelog/compile'
import { writeChangelog } from '../changelog'
import { loadConfig } from '../config/load'
import { channelNames, producesArtifacts, type Config } from '../config/schema'
import { explainReport } from '../explain'
import { currentBranch, isGitRepo } from '../git'
import { installHook, uninstallHook } from '../hook'
import {
  CARGO_RUNNERS,
  detectCi,
  detectEcosystem,
  ECOSYSTEMS,
  init,
  initFiles,
  type Ecosystem,
} from '../init'
import { plan, PlanRefusal } from '../plan'
import { platformAdvice, probeTargets } from '../platforms'
import { summarize } from '../summarize'
import {
  die,
  parse,
  preScan,
  resolveAdapter,
  resolveRoot,
  VERSION,
} from './args'

/**
 * `--force` names the files it is about to replace, and asks.
 *
 * **Because a workflow is not a scaffold after the first day.** Everything
 * generated by `init` is meant to be edited — the gates are blank on purpose,
 * the comments say which blocks are yours — so by the time anyone reaches for
 * `--force` the file usually contains work. Worse than losing it: where npm
 * trusted publishing names `publish.yml`, replacing that file breaks publishing
 * outright, and the failure shows up on the next release rather than now.
 *
 * The flag stays, and it is still the right answer after adding a channel. It
 * just says what it costs first.
 *
 * Not a terminal — CI, a script — proceeds. `--force` was typed explicitly, and
 * a prompt nobody can answer would hang a pipeline instead of protecting it.
 */
async function confirmForce(
  root: string,
  eco: Ecosystem,
  config: Config,
): Promise<void> {
  const at = new Set<string>()
  for (const file of initFiles(eco, VERSION, config)) {
    // `onlyIfAbsent` files are never replaced, with or without the flag.
    if (file.onlyIfAbsent) continue
    if (await Bun.file(`${root}/${file.path}`).exists()) at.add(file.path)
  }

  if (!at.size) return

  console.error(
    `cutver: --force will overwrite ${at.size} file(s), losing any edits:`,
  )
  for (const path of at) console.error(`          ${path}`)
  console.error(
    '\n        These are meant to be edited — your gates live in version.yml, and\n' +
      '        publish.yml is named in npm trusted-publisher configuration where\n' +
      '        that is set up, so replacing it can break publishing.\n' +
      '        Docs: https://cutver.okyle.dev/#/getting-started/ci',
  )

  if (!process.stdin.isTTY) {
    console.error(
      '\n        Not a terminal — proceeding, since --force was explicit.',
    )
    return
  }

  if (!confirm('        Overwrite them?')) die('nothing written')
}

/**
 * `cutver init <cargo|node|bun>`.
 *
 * Deliberately does not require a git repository. Scaffolding the workflows is
 * the one thing here that makes sense in a tree that has not been initialised
 * yet, and refusing would send people to write the files by hand — which is
 * how the two gotchas in them get lost.
 */
export async function runInit(argv: string[]): Promise<void> {
  const opts = parse(argv, [], 'init')
  const root = resolveRoot(opts.cwd)

  // **Asked before anything is written, because writing is the wrong answer
  // here.** cutver generates GitHub Actions and nothing else, so a repository
  // that already runs its CI somewhere else would get two workflow files in a
  // directory that system never reads — present, plausible, and never run.
  // Naming the provider it found beats scaffolding over it.
  const ci = await detectCi(root)
  if (ci && ci.id !== 'github') {
    die(
      `this repository uses ${ci.name} (${ci.path}), and cutver only generates\n` +
        '        GitHub Actions. The workflows would sit in .github/workflows,\n' +
        `        which ${ci.name} does not read.\n\n` +
        '        cutver itself works anywhere — `cutver stage --if-needed` is one\n' +
        '        step in any CI. Generate the pair somewhere scratch to read what\n' +
        '        they do, then port the two jobs:\n' +
        '          cutver init --cwd /tmp/scratch --no-hook',
    )
  }

  const eco = opts.explicit ?? (await detectEcosystem(root))

  if (!eco || !(ECOSYSTEMS as readonly string[]).includes(eco)) {
    // Detection returns `null` for the two cases where guessing bumps the wrong
    // file — no manifest, or both — so the message names which one it is.
    const both =
      !opts.explicit &&
      (await Bun.file(`${root}/Cargo.toml`).exists()) &&
      (await Bun.file(`${root}/package.json`).exists())

    die(
      opts.explicit
        ? `'${opts.explicit}' is not an ecosystem — cutver knows ${ECOSYSTEMS.join(', ')}`
        : both
          ? `${root} has both a Cargo.toml and a package.json.\n` +
            `        Say which this release is about: \`cutver init ` +
            `${ECOSYSTEMS.join('|')}\`.`
          : `no package.json or Cargo.toml in ${root}, so there is nothing to\n` +
            `        detect. Name one: \`cutver init ${ECOSYSTEMS.join('|')}\`.`,
    )
  }

  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  if (opts.force && !opts.dryRun)
    await confirmForce(root, eco as Ecosystem, config)

  const results = await init(root, eco as Ecosystem, {
    force: opts.force,
    dryRun: opts.dryRun,
    hook: !opts.noHook,
    version: VERSION,
    config,
  })

  console.log(
    `cutver: ${root} ` +
      `(${eco})${opts.dryRun ? ' — dry run, nothing written' : ''}`,
  )
  const width = Math.max(...results.map(r => r.path.length))
  for (const r of results) {
    console.log(
      `  ${r.state === 'written' ? '↑' : '='} ${r.path.padEnd(width)}  ` +
        `${r.detail}`,
    )
  }

  // A new devDependency and an unchanged lockfile disagree, and the generated
  // workflow installs with `--frozen-lockfile` — so the very first CI run
  // would fail on the dependency this command just added. Say it first,
  // because it is the only step that breaks something if skipped.
  const pinned = results.find(
    r => r.path === 'package.json' && r.state === 'written',
  )
  if (pinned) {
    console.log(
      `\n  first: run your package manager's install. ${pinned.detail} is in\n` +
        '         package.json and not yet in the lockfile, and the generated\n' +
        '         workflow installs with --frozen-lockfile.',
    )
  }

  // **Asked here rather than guessed at write time.** cutver cannot know
  // whether a workspace builds on all three runners it just scaffolded — the
  // thing that stops it is a system library, which no manifest mentions. So the
  // dependency graph is resolved per target and anything that goes looking for
  // a preinstalled library is named. Costs three cargo invocations and turns a
  // failure that arrives after a public tag into a line of output here.
  if (
    ADAPTER_FOR[eco as Ecosystem] === 'cargo' &&
    producesArtifacts('cargo', config)
  ) {
    const notes = await probeTargets(
      root,
      CARGO_RUNNERS.map(r => r.target),
    )
    for (const line of platformAdvice(notes)) console.log(line)
  }

  console.log(
    '\n  next:  read both workflows — the comments in them are the reasons, not\n' +
      '         decoration. Set your gates in version.yml; cutver cannot know\n' +
      '         what they are. Release one is published by hand: a trusted\n' +
      '         publisher cannot create a package that does not exist yet.',
  )
}

/**
 * `cutver notes <tag>` — the release body for a tag, on stdout.
 *
 * The section from `CHANGELOG.md`, optionally rewritten by the configured
 * summariser. Read-only, and **never fails over content**: it is one step in a
 * publish job that has already tagged and already built, so failing here would
 * strand a release over release notes. No changelog, no section, no summariser,
 * a summariser that died — every one of those prints what it has, says why on
 * stderr, and lets the publish continue.
 *
 * Its whole reason for existing is that the alternative lives in the generated
 * workflow. Anything baked into `publish.yml` is frozen at `init` time for
 * every repository that already ran it, so improving it later means asking
 * everyone to regenerate a file they have since hand-edited. Here, `bunx
 * cutver` picks up the improvement on the next release and the workflow line
 * never changes.
 */
export async function runNotes(argv: string[]): Promise<void> {
  const rest = argv.filter(a => a !== 'notes')
  const opts = parse(rest, undefined, 'notes')
  const args = opts.positional
  const [first, second] = args

  if (!first)
    die(
      'notes needs a tag, or a range — `cutver notes v1.2.3` / `cutver notes ' +
        'v1.2.0 v1.3.0`',
    )
  if (args.length > 2)
    die(`notes takes a tag or a range, not ${args.length} arguments`)

  const root = resolveRoot(opts.cwd)
  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  // **Two forms, because they answer different questions.**
  //
  // `notes <tag>` reads the changelog, so the body on the release page is the
  // same words as the file in the repository — which is the point of taking it
  // from there rather than generating a second telling.
  //
  // `notes <from> <to>` compiles the range straight from git and never looks at
  // the changelog. That is the form for a repository that keeps no changelog at
  // all, where the alternative is an empty release body, and for backfilling a
  // release that predates any of this.
  const body = second
    ? await compileRange(root, first, second, config)
    : await sectionOrCompile(root, first, config)

  if (!body) return

  // Full bodies only where a model will read them — see `fullBodies` on why the
  // summariser is sent more than the release shows. `body` stays the fallback:
  // a dead model must publish the prose somebody wrote, never a raw dump of
  // every commit body.
  // `with_body` decides how much of each commit travels: whole bodies, which
  // is what lets one commit become several bullets, or the rendered section.
  const summarizer = config.changelog?.summarizer
  const withBody = summarizer === true || (summarizer?.withBody ?? true)

  const raw =
    summarizer && withBody
      ? await fullBodies(root, first, second, config)
      : null

  const { text, note } = await summarize(
    raw?.commits ?? body,
    config.changelog,
    Bun.env,
    body,
    raw?.metadata ?? null,
  )
  if (note) console.error(`cutver: ${note}`)
  console.log(text)
}

/**
 * `cutver check` — is this branch allowed to release what its commits imply?
 *
 * Read-only, offline, and with exit codes suited to a hook rather than to a
 * person: **0 for "nothing to release"**, which is not a problem and must not
 * block a push, and 1 only for the branch-declared refusal.
 *
 * Anything else — cutver crashed, git is broken, the manifest will not parse —
 * also exits 0, loudly. A guard that fails closed on its own bug blocks every
 * push in the repository, and CI still catches the real thing.
 */
export async function runCheck(argv: string[]): Promise<void> {
  const pre = preScan(argv)
  const root = resolveRoot(pre.cwd)

  try {
    // The config is loaded inside the try on purpose: a repository with a
    // broken or too-new config must not have every push blocked by it. A
    // ConfigError is not a PlanRefusal, so the catch below lets the push
    // through and says why.
    const { config } = await loadConfig(root, pre.config)
    const opts = parse(argv, channelNames(config), 'check')
    const rev = opts.rev ?? 'HEAD'
    // Both of these are ordinary states rather than errors — a hook lives in
    // repositories cutver was never set up for — so they are named plainly
    // instead of arriving as a stack trace about `undefined`.
    if (!(await isGitRepo(root))) {
      console.error(`cutver: check skipped — ${root} is not a git repository`)
      return
    }
    const ids = await applicableAdapters(root)
    if (!opts.adapter && !ids.length) {
      console.error(
        'cutver: check skipped — no package.json or Cargo.toml here',
      )
      return
    }

    const adapter = ADAPTERS[(await resolveAdapter(root, opts, config)).id]
    const branch = opts.branch ?? (await currentBranch(root))
    const decision = await plan({
      root,
      current: await adapter.readVersion(root),
      branch,
      channel: opts.channel,
      rev,
      config,
    })

    // **`no-rule` exits 0 here, and that is the whole reason it is a Plan
    // variant rather than a PlanRefusal.** This runs from the pre-push hook on
    // every branch of every push; refusing an unmatched branch would block
    // every feature branch in the repository, forever.
    console.log(
      decision.kind === 'release'
        ? `cutver: check ok — '${branch}' would release ${decision.version}`
        : `cutver: check ok — '${branch}' releases nothing (${decision.why})`,
    )
  } catch (e) {
    if (e instanceof PlanRefusal) {
      console.error(`cutver: ${e.message}`)
      console.error('        Push with --no-verify if the branch is right.')
      process.exit(1)
    }
    // Not the refusal. Say so and get out of the way.
    console.error(`cutver: check skipped — ${(e as Error).message}`)
  }
}

/** `cutver hook install|uninstall`. */
export async function runHook(argv: string[]): Promise<void> {
  const action = argv[0]
  if (action !== 'install' && action !== 'uninstall') {
    die('hook takes `install` or `uninstall`')
  }

  const opts = parse(argv.slice(1), undefined, 'hook')
  const root = resolveRoot(opts.cwd)
  if (!(await isGitRepo(root))) die(`${root} is not a git repository`)

  const result =
    action === 'install'
      ? await installHook(root, {
          force: opts.force,
          dryRun: opts.dryRun,
          runner: opts.runner,
          version: VERSION,
        })
      : await uninstallHook(root, { dryRun: opts.dryRun })

  console.log(
    `cutver: ${result.state === 'written' ? '↑' : '='} ${result.path}  ${result.detail}` +
      (opts.dryRun ? ' (dry run)' : ''),
  )

  if (action === 'install' && result.state === 'written') {
    console.log(
      '\n  It refuses a push to a release branch whose name promises a lower\n' +
        '  version than its commits justify. Everything else it lets through —\n' +
        '  including its own failures. `git push --no-verify` bypasses it.',
    )
  }
}

/**
 * `cutver explain` — read-only, offline, and always exit 0.
 *
 * Same posture as `check`, for the same reason: it is a diagnostic, and a
 * diagnostic that can fail is one more thing to diagnose.
 */
export async function runExplain(argv: string[]): Promise<void> {
  const pre = preScan(argv)
  const root = resolveRoot(pre.cwd)

  try {
    const { config } = await loadConfig(root, pre.config)
    const opts = parse(argv, channelNames(config), 'explain')
    const adapter = await resolveAdapter(root, opts, config)
    const branch = opts.branch ?? (await currentBranch(root))

    let summary: string | null = null
    try {
      const decision = await plan({
        root,
        current: await ADAPTERS[adapter.id].readVersion(root),
        branch,
        channel: opts.channel,
        config,
      })
      summary =
        decision.kind === 'release'
          ? `${decision.from} -> ${decision.version} (${decision.why})`
          : decision.why
    } catch (e) {
      summary = `REFUSED — ${(e as Error).message.split('\n')[0]}`
    }

    for (const line of explainReport({
      root,
      branch,
      config,
      adapter: adapter.id,
      adapterFrom: adapter.from,
      plan: summary,
    })) {
      console.log(line)
    }
  } catch (e) {
    console.error(`cutver: ${(e as Error).message}`)
  }
}

/**
 * `cutver changelog` — rebuild the file from the tags, release nothing.
 *
 * **The changelog is otherwise only written when a version is cut**, which
 * leaves no way to adopt `changelog:` on an existing project, change `keep` or
 * `sections`, or pick up a better rendering — short of cutting a release you
 * did not want.
 *
 * Nothing but `CHANGELOG.md` is touched: no manifest, no tag, no version. It is
 * the one command here that changes a file without claiming a release happened.
 *
 * Was `--regenerate-changelogs`, which still works and says what it became.
 */
export async function runChangelog(argv: string[]): Promise<void> {
  const rest = argv.filter(a => a !== 'changelog')
  const opts = parse(rest, undefined, 'changelog')
  const root = resolveRoot(opts.cwd)
  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  if (!config.changelog) {
    die(
      'nothing to regenerate — `changelog:` is not set, so cutver does not own\n' +
        '        CHANGELOG.md and will not overwrite what you wrote.\n' +
        '        Docs: https://cutver.okyle.dev/#/guides/changelog',
    )
  }

  const releases = await compileReleases(
    root,
    null,
    config.changelog.sections,
    config.changelog.prereleases,
  )
  if (!releases.length) {
    die('no `v*` tags — there are no releases to compile a changelog from')
  }

  const change = await writeChangelog({
    root,
    dryRun: opts.dryRun,
    keep: config.changelog.keep,
    releases,
  })

  console.log(
    `cutver: ${root}${opts.dryRun ? ' (dry run — nothing is written)' : ''}`,
  )
  console.log(`  ${opts.dryRun ? '=' : '↑'} CHANGELOG.md  ${change.detail}`)
}

/**
 * `cutver config` — what cutver actually believes, rather than what the file
 * says.
 *
 * **Every default filled in and every channel normalised**, which is the point:
 * a key that was ignored because it was misspelt is visible by its absence, and
 * a channel written `myPrefix` appears as the `my-prefix` that the version
 * string, the tag and the dist-tag will all use.
 *
 * JSON rather than YAML, because it is a format cutver also reads — the output
 * can be saved as `cutver.json` and mean exactly what it just described. Reads
 * no git and touches no network.
 */
export async function runConfig(argv: string[]): Promise<void> {
  const opts = parse(
    argv.filter(a => a !== 'config'),
    undefined,
    'config',
  )
  const root = resolveRoot(opts.cwd)
  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  // `source` is where it was read from, not something you can write back, so it
  // is reported on stderr and kept out of the document on stdout. That keeps
  // `cutver config > cutver.json` honest.
  console.error(
    `cutver: ${config.source ?? 'no config file — these are the defaults'}`,
  )
  const { source: _source, ...document } = config
  console.log(JSON.stringify(document, null, 2))
}
