/**
 * The subcommands: `init`, `notes`, `changelog`, `check`, `explain`, `hook` and
 * `config`.
 *
 * **What they have in common is what the bare `cutver` does not:** none of them
 * cuts a version. Four are read-only or write one file, and their exit codes
 * answer to a hook or a publish job rather than to a person at a prompt. The
 * release sequence lives in `stage.ts` because it is the one path where an
 * early exit means a half-released repository.
 */
import { ADAPTER_FOR, ADAPTERS, applicableAdapters } from '../adapters'
import {
  compileRange,
  compileReleases,
  fullBodies,
  sectionOrCompile,
} from '../changelog/compile'
import { writeChangelog } from '../changelog'
import {
  githubRepo,
  isUnauthored,
  listReleases,
  resolveToken,
  updateRelease,
  type ReleaseUpdate,
} from '../changelog/releases'
import { loadConfig } from '../config/load'
import { channelNames, producesArtifacts, type Config } from '../config/schema'
import { explainReport } from '../explain'
import { currentBranch, isGitRepo, releaseTags } from '../git'
import { installHook, uninstallHook } from '../hook'
import {
  CARGO_RUNNERS,
  detectCi,
  detectEcosystem,
  ECOSYSTEMS,
  init,
  initFiles,
  type Ecosystem,
} from '../init'
import { plan, PlanRefusal } from '../plan'
import { platformAdvice, probeTargets } from '../platforms'
import { summarize } from '../summarize'
import {
  die,
  parse,
  preScan,
  resolveAdapter,
  resolveRoot,
  VERSION,
} from './args'
import { env, exists } from '../runtime'
import { say } from './style'

/**
 * `--force` names the files it is about to replace, and asks.
 *
 * **Because a workflow is not a scaffold after the first day.** Everything
 * generated by `init` is meant to be edited — the gates are blank on purpose,
 * the comments say which blocks are yours — so by the time anyone reaches for
 * `--force` the file usually contains work. Worse than losing it: where npm
 * trusted publishing names `publish.yml`, replacing that file breaks publishing
 * outright, and the failure shows up on the next release rather than now.
 *
 * The flag stays, and it is still the right answer after adding a channel. It
 * just says what it costs first.
 *
 * Not a terminal — CI, a script — proceeds. `--force` was typed explicitly, and
 * a prompt nobody can answer would hang a pipeline instead of protecting it.
 */
async function confirmForce(
  root: string,
  eco: Ecosystem,
  config: Config,
): Promise<void> {
  const at = new Set<string>()
  for (const file of initFiles(eco, VERSION, config)) {
    // `onlyIfAbsent` files are never replaced, with or without the flag.
    if (file.onlyIfAbsent) continue
    if (await exists(`${root}/${file.path}`)) at.add(file.path)
  }

  if (!at.size) return

  console.error(
    `cutver: --force will overwrite ${at.size} file(s), losing any edits:`,
  )
  for (const path of at) console.error(`          ${path}`)
  console.error(
    '\n        These are meant to be edited — your gates live in version.yml, and\n' +
      '        publish.yml is named in npm trusted-publisher configuration where\n' +
      '        that is set up, so replacing it can break publishing.\n' +
      '        Docs: https://cutver.okyle.dev/#/getting-started/ci',
  )

  if (!process.stdin.isTTY) {
    console.error(
      '\n        Not a terminal — proceeding, since --force was explicit.',
    )
    return
  }

  if (!confirm('        Overwrite them?')) die('nothing written')
}

/**
 * `cutver init <cargo|node|bun>`.
 *
 * Deliberately does not require a git repository. Scaffolding the workflows is
 * the one thing here that makes sense in a tree that has not been initialised
 * yet, and refusing would send people to write the files by hand — which is
 * how the two gotchas in them get lost.
 */
export async function runInit(argv: string[]): Promise<void> {
  const opts = parse(argv, [], 'init')
  const root = resolveRoot(opts.cwd)

  // **Asked before anything is written, because writing is the wrong answer
  // here.** cutver generates GitHub Actions and nothing else, so a repository
  // that already runs its CI somewhere else would get two workflow files in a
  // directory that system never reads — present, plausible, and never run.
  // Naming the provider it found beats scaffolding over it.
  const ci = await detectCi(root)
  if (ci && ci.id !== 'github') {
    die(
      `this repository uses ${ci.name} (${ci.path}), and cutver only generates\n` +
        '        GitHub Actions. The workflows would sit in .github/workflows,\n' +
        `        which ${ci.name} does not read.\n\n` +
        '        cutver itself works anywhere — `cutver stage --if-needed` is one\n' +
        '        step in any CI. Generate the pair somewhere scratch to read what\n' +
        '        they do, then port the two jobs:\n' +
        '          cutver init --cwd /tmp/scratch --no-hook',
    )
  }

  const eco = opts.explicit ?? (await detectEcosystem(root))

  if (!eco || !(ECOSYSTEMS as readonly string[]).includes(eco)) {
    // Detection returns `null` for the two cases where guessing bumps the wrong
    // file — no manifest, or both — so the message names which one it is.
    const both =
      !opts.explicit &&
      (await exists(`${root}/Cargo.toml`)) &&
      (await exists(`${root}/package.json`))

    die(
      opts.explicit
        ? `'${opts.explicit}' is not an ecosystem — cutver knows ${ECOSYSTEMS.join(', ')}`
        : both
          ? `${root} has both a Cargo.toml and a package.json.\n` +
            `        Say which this release is about: \`cutver init ` +
            `${ECOSYSTEMS.join('|')}\`.`
          : `no package.json or Cargo.toml in ${root}, so there is nothing to\n` +
            `        detect. Name one: \`cutver init ${ECOSYSTEMS.join('|')}\`.`,
    )
  }

  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  if (opts.force && !opts.dryRun)
    await confirmForce(root, eco as Ecosystem, config)

  const results = await init(root, eco as Ecosystem, {
    force: opts.force,
    dryRun: opts.dryRun,
    hook: !opts.noHook,
    version: VERSION,
    config,
  })

  console.log(
    `cutver: ${root} ` +
      `(${eco})${opts.dryRun ? ' — dry run, nothing written' : ''}`,
  )
  const width = Math.max(...results.map(r => r.path.length))
  for (const r of results) {
    console.log(
      `  ${r.state === 'written' ? '↑' : '='} ${r.path.padEnd(width)}  ` +
        `${r.detail}`,
    )
  }

  // A new devDependency and an unchanged lockfile disagree, and the generated
  // workflow installs with `--frozen-lockfile` — so the very first CI run
  // would fail on the dependency this command just added. Say it first,
  // because it is the only step that breaks something if skipped.
  const pinned = results.find(
    r => r.path === 'package.json' && r.state === 'written',
  )
  if (pinned) {
    console.log(
      `\n  first: run your package manager's install. ${pinned.detail} is in\n` +
        '         package.json and not yet in the lockfile, and the generated\n' +
        '         workflow installs with --frozen-lockfile.',
    )
  }

  // **Asked here rather than guessed at write time.** cutver cannot know
  // whether a workspace builds on all three runners it just scaffolded — the
  // thing that stops it is a system library, which no manifest mentions. So the
  // dependency graph is resolved per target and anything that goes looking for
  // a preinstalled library is named. Costs three cargo invocations and turns a
  // failure that arrives after a public tag into a line of output here.
  if (
    ADAPTER_FOR[eco as Ecosystem] === 'cargo' &&
    producesArtifacts('cargo', config)
  ) {
    const notes = await probeTargets(
      root,
      CARGO_RUNNERS.map(r => r.target),
    )
    for (const line of platformAdvice(notes)) console.log(line)
  }

  console.log(
    '\n  next:  read both workflows — the comments in them are the reasons, not\n' +
      '         decoration. Set your gates in version.yml; cutver cannot know\n' +
      '         what they are. Release one is published by hand: a trusted\n' +
      '         publisher cannot create a package that does not exist yet.',
  )
}

/**
 * `cutver notes <tag>` — the release body for a tag, on stdout.
 *
 * The section from `CHANGELOG.md`, optionally rewritten by the configured
 * summariser. Read-only, and **never fails over content**: it is one step in a
 * publish job that has already tagged and already built, so failing here would
 * strand a release over release notes. No changelog, no section, no summariser,
 * a summariser that died — every one of those prints what it has, says why on
 * stderr, and lets the publish continue.
 *
 * Its whole reason for existing is that the alternative lives in the generated
 * workflow. Anything baked into `publish.yml` is frozen at `init` time for
 * every repository that already ran it, so improving it later means asking
 * everyone to regenerate a file they have since hand-edited. Here, `bunx
 * cutver` picks up the improvement on the next release and the workflow line
 * never changes.
 */
export async function runNotes(argv: string[]): Promise<void> {
  const rest = argv.filter(a => a !== 'notes')
  const opts = parse(rest, undefined, 'notes')
  const args = opts.positional
  const [first, second] = args

  if (!first)
    die(
      'notes needs a tag, or a range — `cutver notes v1.2.3` / `cutver notes ' +
        'v1.2.0 v1.3.0`',
    )
  if (args.length > 2)
    die(`notes takes a tag or a range, not ${args.length} arguments`)

  const root = resolveRoot(opts.cwd)
  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  // **Two forms, because they answer different questions.**
  //
  // `notes <tag>` reads the changelog, so the body on the release page is the
  // same words as the file in the repository — which is the point of taking it
  // from there rather than generating a second telling.
  //
  // `notes <from> <to>` compiles the range straight from git and never looks at
  // the changelog. That is the form for a repository that keeps no changelog at
  // all, where the alternative is an empty release body, and for backfilling a
  // release that predates any of this.
  const body = second
    ? await compileRange(root, first, second, config)
    : await sectionOrCompile(root, first, config)

  if (!body) return

  // Full bodies only where a model will read them — see `fullBodies` on why the
  // summariser is sent more than the release shows. `body` stays the fallback:
  // a dead model must publish the prose somebody wrote, never a raw dump of
  // every commit body.
  // `with_body` decides how much of each commit travels: whole bodies, which
  // is what lets one commit become several bullets, or the rendered section.
  const summarizer = config.changelog?.summarizer
  const withBody = summarizer === true || (summarizer?.withBody ?? true)

  const raw =
    summarizer && withBody
      ? await fullBodies(root, first, second, config)
      : null

  const { text, note } = await summarize(
    raw?.commits ?? body,
    config.changelog,
    env,
    body,
    raw?.metadata ?? null,
  )
  if (note) console.error(`cutver: ${note}`)
  console.log(text)
}

/**
 * `cutver check` — is this branch allowed to release what its commits imply?
 *
 * Read-only, offline, and with exit codes suited to a hook rather than to a
 * person: **0 for "nothing to release"**, which is not a problem and must not
 * block a push, and 1 only for the branch-declared refusal.
 *
 * Anything else — cutver crashed, git is broken, the manifest will not parse —
 * also exits 0, loudly. A guard that fails closed on its own bug blocks every
 * push in the repository, and CI still catches the real thing.
 */
export async function runCheck(argv: string[]): Promise<void> {
  const pre = preScan(argv)
  const root = resolveRoot(pre.cwd)

  try {
    // The config is loaded inside the try on purpose: a repository with a
    // broken or too-new config must not have every push blocked by it. A
    // ConfigError is not a PlanRefusal, so the catch below lets the push
    // through and says why.
    const { config } = await loadConfig(root, pre.config)
    const opts = parse(argv, channelNames(config), 'check')
    const rev = opts.rev ?? 'HEAD'
    // Both of these are ordinary states rather than errors — a hook lives in
    // repositories cutver was never set up for — so they are named plainly
    // instead of arriving as a stack trace about `undefined`.
    if (!(await isGitRepo(root))) {
      console.error(`cutver: check skipped — ${root} is not a git repository`)
      return
    }
    const ids = await applicableAdapters(root)
    if (!opts.adapter && !ids.length) {
      console.error(
        'cutver: check skipped — no package.json or Cargo.toml here',
      )
      return
    }

    const adapter = ADAPTERS[(await resolveAdapter(root, opts, config)).id]
    const branch = opts.branch ?? (await currentBranch(root))
    const decision = await plan({
      root,
      current: await adapter.readVersion(root),
      branch,
      channel: opts.channel,
      rev,
      config,
    })

    // **`no-rule` exits 0 here, and that is the whole reason it is a Plan
    // variant rather than a PlanRefusal.** This runs from the pre-push hook on
    // every branch of every push; refusing an unmatched branch would block
    // every feature branch in the repository, forever.
    console.log(
      decision.kind === 'release'
        ? `cutver: check ok — '${branch}' would release ${decision.version}`
        : `cutver: check ok — '${branch}' releases nothing (${decision.why})`,
    )
  } catch (e) {
    if (e instanceof PlanRefusal) {
      console.error(`cutver: ${e.message}`)
      console.error('        Push with --no-verify if the branch is right.')
      process.exit(1)
    }
    // Not the refusal. Say so and get out of the way.
    console.error(`cutver: check skipped — ${(e as Error).message}`)
  }
}

/** `cutver hook install|uninstall`. */
export async function runHook(argv: string[]): Promise<void> {
  const action = argv[0]
  if (action !== 'install' && action !== 'uninstall') {
    die('hook takes `install` or `uninstall`')
  }

  const opts = parse(argv.slice(1), undefined, 'hook')
  const root = resolveRoot(opts.cwd)
  if (!(await isGitRepo(root))) die(`${root} is not a git repository`)

  const result =
    action === 'install'
      ? await installHook(root, {
          force: opts.force,
          dryRun: opts.dryRun,
          runner: opts.runner,
          version: VERSION,
        })
      : await uninstallHook(root, { dryRun: opts.dryRun })

  console.log(
    `cutver: ${result.state === 'written' ? '↑' : '='} ${result.path}  ${result.detail}` +
      (opts.dryRun ? ' (dry run)' : ''),
  )

  if (action === 'install' && result.state === 'written') {
    console.log(
      '\n  It refuses a push to a release branch whose name promises a lower\n' +
        '  version than its commits justify. Everything else it lets through —\n' +
        '  including its own failures. `git push --no-verify` bypasses it.',
    )
  }
}

/**
 * `cutver explain` — read-only, offline, and always exit 0.
 *
 * Same posture as `check`, for the same reason: it is a diagnostic, and a
 * diagnostic that can fail is one more thing to diagnose.
 */
export async function runExplain(argv: string[]): Promise<void> {
  const pre = preScan(argv)
  const root = resolveRoot(pre.cwd)

  try {
    const { config } = await loadConfig(root, pre.config)
    const opts = parse(argv, channelNames(config), 'explain')
    const adapter = await resolveAdapter(root, opts, config)
    const branch = opts.branch ?? (await currentBranch(root))

    let summary: string | null = null
    try {
      const decision = await plan({
        root,
        current: await ADAPTERS[adapter.id].readVersion(root),
        branch,
        channel: opts.channel,
        config,
      })
      summary =
        decision.kind === 'release'
          ? `${decision.from} -> ${decision.version} (${decision.why})`
          : decision.why
    } catch (e) {
      summary = `REFUSED — ${(e as Error).message.split('\n')[0]}`
    }

    for (const line of explainReport({
      root,
      branch,
      config,
      adapter: adapter.id,
      adapterFrom: adapter.from,
      plan: summary,
    })) {
      console.log(line)
    }
  } catch (e) {
    console.error(`cutver: ${(e as Error).message}`)
  }
}

/**
 * `cutver changelog` — rebuild the file from the tags, release nothing.
 *
 * **The changelog is otherwise only written when a version is cut**, which
 * leaves no way to adopt `changelog:` on an existing project, change `keep` or
 * `sections`, or pick up a better rendering — short of cutting a release you
 * did not want.
 *
 * Nothing but `CHANGELOG.md` is touched: no manifest, no tag, no version. It is
 * the one command here that changes a file without claiming a release happened.
 *
 * Was `--regenerate-changelogs`, which still works and says what it became.
 */
export async function runChangelog(argv: string[]): Promise<void> {
  const rest = argv.filter(a => a !== 'changelog')
  const opts = parse(rest, undefined, 'changelog')
  const root = resolveRoot(opts.cwd)

  // **Two targets, because they are two jobs.** `--overwrite` read as a
  // modifier and was a second command wearing a flag's clothes: the file is a
  // narrative with a length, a release page is one per tag, and the day
  // `changelog.file: false` arrived they stopped even sharing a subject.
  //
  // `regenerate` is not a word here on purpose. A noun-verb grammar earns its
  // keep when a noun has more than one verb; this one has exactly one, so the
  // verb would be ceremony on every invocation.
  const [target, selector] = opts.positional
  if (target !== undefined && target !== 'file' && target !== 'pages') {
    die(
      `\`cutver changelog ${target}\` is not a target — it is \`file\` or \`pages\`.\n` +
        '          cutver changelog file            rebuild CHANGELOG.md\n' +
        '          cutver changelog pages           the tags the file lists\n' +
        '          cutver changelog pages all       every tag, prereleases too\n' +
        '          cutver changelog pages 5         the newest five\n' +
        '          cutver changelog pages v1.2.0    just that one',
    )
  }
  if (target !== 'pages' && selector !== undefined) {
    die(`\`${selector}\` is a selector, and only \`pages\` takes one`)
  }

  // `--overwrite` did both halves, so the alias keeps doing both. Anyone
  // following the warning to `pages` gets the pages alone, which is the point
  // of naming them separately.
  const wantsFile = target !== 'pages'
  const wantsPages = target === 'pages' || opts.overwrite
  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  if (!config.changelog) {
    die(
      'nothing to regenerate — `changelog:` is not set, so cutver does not own\n' +
        '        CHANGELOG.md and will not overwrite what you wrote.\n' +
        '        Docs: https://cutver.okyle.dev/#/guides/changelog',
    )
  }

  // **Compiled only when something asks for it.** Reading a release costs a
  // `git log` and two `rev-parse`s, so the file's whole list is built when the
  // file is being written — or when `pages` has no selector and therefore means
  // "the ones the file lists". Naming a version asks for one section, and used
  // to build every one twice over to find it.
  const needsList = wantsFile

  const releases = needsList
    ? await compileReleases(
        root,
        null,
        config.changelog.sections,
        config.changelog.prereleases,
      )
    : []

  if (needsList && !releases.length) {
    die('no `v*` tags — there are no releases to compile a changelog from')
  }

  // **`file: false` means the pages are the whole job.** Asking to rebuild a
  // file this config says cutver does not own is a request with no honest
  // answer, so it is refused rather than quietly doing half of it.
  if (wantsFile && !config.changelog.file) {
    die(
      'nothing to rebuild — `changelog.file` is false, so cutver does not write\n' +
        '        CHANGELOG.md. The pages are the job here:\n' +
        '          cutver changelog pages',
    )
  }

  console.log(
    `cutver: ${root}${opts.dryRun ? ' (dry run — nothing is written)' : ''}`,
  )

  if (wantsFile) {
    const change = await writeChangelog({
      root,
      dryRun: opts.dryRun,
      keep: config.changelog.keep,
      releases,
    })
    console.log(`  ${opts.dryRun ? '=' : '↑'} CHANGELOG.md  ${change.detail}`)
  }

  if (wantsPages) {
    await overwriteReleases(
      root,
      config,
      await candidateVersions(root, config.changelog.prereleases, selector),
      // **Compiled on demand, and only for the pages that need writing.**
      // Which ones those are is a question about the *old* body, so it is
      // answered from one listing before any of this runs. Anything already
      // compiled for the file is reused rather than read twice.
      async only => {
        const sections = config.changelog?.sections ?? []
        const have = new Map(releases.map(r => [r.version, r.notes]))
        const missing = [...only].filter(v => !have.has(v))
        if (missing.length) {
          const built = await compileReleases(
            root,
            null,
            sections,
            true,
            new Set(missing),
          )
          for (const r of built) have.set(r.version, r.notes)
        }
        return have
      },
      opts.dryRun,
      opts.force,
    )
  }
}

/**
 * Which tags a selector names — decided from the tag list, nothing compiled.
 *
 * **`keep` and `prereleases` describe the file, not these.** The file is a
 * narrative with a length; a page is one per tag. With `prereleases: false` an
 * alpha's commits fold into the stable release that ships them — right for the
 * file, and it leaves the alpha itself with no page, though it is a version
 * somebody installed through a dist-tag and can land on from a link.
 *
 * So the default stays what `--overwrite` always did — the tags the file lists
 * — and every wider answer is asked for by name.
 *
 * Answered from `releaseTags`, which is one `for-each-ref`. Answering it from
 * compiled sections instead is what made `pages v1.2.0` read twenty-five
 * releases to keep one, at a `git log` and two `rev-parse`s each.
 */
async function candidateVersions(
  root: string,
  prereleases: boolean,
  selector: string | undefined,
): Promise<string[]> {
  const tags = await releaseTags(root)
  if (!tags.length) {
    die('no `v*` tags — there are no releases to write a page for')
  }

  // No selector means "the tags the file lists", which is the same filter
  // `compileReleases` applies — and knowable from the tag names alone, so the
  // default no longer builds the whole file to find out what it covers.
  if (selector === undefined) {
    return tags
      .filter(t => prereleases || !t.version.includes('-'))
      .map(t => t.version)
  }

  if (selector === 'all') return tags.map(t => t.version)

  if (/^\d+$/.test(selector)) {
    const count = Number(selector)
    if (count < 1) die('a count has to be at least 1')
    return tags.slice(0, count).map(t => t.version)
  }

  // A version, with or without the `v` the tag carries.
  const version = selector.replace(/^v/, '')
  if (!tags.some(t => t.version === version)) {
    die(
      `no tag for \`${selector}\`.\n` +
        `        Tags cutver can write a page for: ${tags
          .slice(0, 5)
          .map(t => t.tag)
          .join(', ')}${tags.length > 5 ? ', …' : ''}`,
    )
  }
  return [version]
}

/**
 * `--overwrite` — carry the compiled sections onto the release pages too.
 *
 * **The file and the release pages drift apart the moment `changelog:` is
 * adopted.** Rewriting the file fixes every past release in the repository and
 * none of the twenty pages people actually land on from a link.
 *
 * Nothing authored is replaced — see `isUnauthored`. A body a person wrote is
 * published prose that GitHub keeps no history of, so the rule is not "replace
 * unless it looks important", it is "replace only when it provably is not".
 * Every other outcome is a line in the report rather than a silence.
 */
async function overwriteReleases(
  root: string,
  config: Config,
  /** Versions to consider, newest first. Every one is reported. */
  candidates: string[],
  /** Compiled sections for the versions asked for — called once, if at all. */
  compile: (only: Set<string>) => Promise<Map<string, string>>,
  dryRun: boolean,
  force: boolean,
): Promise<void> {
  const repo = await githubRepo(root)
  if (!repo) {
    console.error(
      'cutver: --overwrite needs a github.com remote — the changelog was still written',
    )
    return
  }

  const { token, from } = await resolveToken(env, root)
  if (!token) {
    console.error(
      'cutver: --overwrite needs a token, and there is none — the changelog was\n' +
        '        still written. Any one of these is enough:\n' +
        '          gh auth login          (cutver reads `gh auth token`)\n' +
        '          export GH_TOKEN=…\n' +
        '        GITHUB_TOKEN is already set in every Actions run.',
    )
    return
  }
  // Said out loud, because it is a credential nobody typed. Somebody running
  // this against the wrong account would otherwise find out from the audit log.
  if (from === 'gh') console.log('cutver: using the token from `gh auth token`')

  // **Asked before anything is compiled.** Whether a page needs writing is
  // decided entirely by the body already on it — missing, empty, generated, or
  // somebody's prose — and none of that needs the new body. One listing answers
  // it for every tag at once, so a run over twenty-five tags where twenty-four
  // are already right reads one section instead of twenty-five, each of which
  // is a `git log` and two `rev-parse`s.
  const existing = await listReleases(repo, token)
  const needed = new Set(
    candidates.filter(version => {
      const body = existing.get(`v${version}`)
      return body === undefined || force || isUnauthored(body, `v${version}`)
    }),
  )

  if (!needed.size) {
    console.log(`\nrelease pages on ${repo}`)
    const width = Math.max(...candidates.map(v => v.length + 1), 4)
    for (const version of candidates) {
      say(
        `  %d·%0 ${`v${version}`.padEnd(width)}  has a written body — left alone (--force replaces it)`,
      )
    }
    return
  }

  // **`--force` destroys published prose, so it asks.** Everything else in this
  // command is safe by construction — a body is replaced only when nobody wrote
  // it. `--force` removes exactly that protection, and GitHub keeps no history
  // of a release body, so there is nothing to restore it from.
  //
  // Not a terminal proceeds, on the same reasoning as `init --force`: the flag
  // was typed explicitly, and a prompt nobody can answer would hang a pipeline
  // instead of protecting it.
  if (force && !dryRun) {
    console.error(
      'cutver: --force will replace release bodies that someone wrote, and\n' +
        '        GitHub keeps no history of them. `--dry-run` lists which.',
    )
    if (process.stdin.isTTY && !confirm('        Replace them?')) {
      die('nothing written to the release pages')
    }
  }

  // **Nothing is compiled for a dry run.** The decision to write, skip or
  // create comes from the body already on the page, and `updateRelease` never
  // asks for a new one when it is not going to send it — so building them is
  // work whose only output is the progress lines it prints on the way.
  const notes = dryRun ? new Map<string, string>() : await compile(needed)

  console.log(`\nrelease pages on ${repo}`)
  const width = Math.max(...candidates.map(v => v.length + 1), 4)

  // Sequential on purpose: GitHub rate-limits by the hour, and a repository
  // with two hundred tags firing two hundred concurrent requests is how a
  // command that was meant to tidy up gets an account throttled. The summariser
  // has the same shape of limit, measured in tokens per minute.
  //
  // **Oldest first, and the report is put back the other way round.** GitHub
  // marks the most recently *created* release as `Latest`, which is what
  // `releases/latest/download` resolves to and what every install script
  // pinned to that URL follows. Walking newest-first created the oldest page
  // last, so backfilling nine tags left `v1.0.0` labelled Latest and
  // `releases/latest` pointing eight versions behind — measured, on the first
  // repository this ran against.
  const rows: { tag: string; result: ReleaseUpdate; note: string | null }[] = []

  for (const version of [...candidates].reverse()) {
    const tag = `v${version}`

    // **Summarised where the release path would summarise.** A page written by
    // `cutver notes` at release time gets the readable version; one written by
    // this command was getting the compiled section, so the same surface read
    // two different ways depending only on when it was filled in.
    //
    // Passed unevaluated — `updateRelease` calls it only once this page is
    // known to be eligible, so the pages it leaves alone cost no inference.
    let note: string | null = null
    const result = await updateRelease(
      repo,
      token,
      tag,
      async () => {
        // Compiled above for everything `needed`; the fallback covers a page
        // that turns out eligible after all, rather than writing an empty body.
        const section =
          notes.get(version) ??
          (await compile(new Set([version]))).get(version) ??
          ''

        // **The `diff:` footnote is handed over, not left in the material.**
        // It opens every compiled section, so the model used to copy it out of
        // `<commits>` — and now it is told not to write one at all, because
        // cutver restores it. Restoring needs it *passed*: without this the
        // page came out with no footnote at all.
        const head = section.split('\n')[0] ?? ''
        const metadata = /^\s*(?:<sub>)?\s*diff:/i.test(head) ? head : null

        const summary = await summarize(
          section,
          config.changelog,
          env,
          section,
          metadata,
        )
        note = summary.note
        return summary.text
      },
      dryRun,
      force,
    )

    rows.push({ tag, result, note })
  }

  // Newest first again, which is the order a changelog is read in.
  for (const { tag, result, note } of rows.reverse()) {
    const mark =
      result.state === 'created'
        ? '%g+%0'
        : result.state === 'updated'
          ? '%g↑%0'
          : result.state === 'skipped'
            ? '%d·%0'
            : '%d=%0'
    say(`  ${mark} ${tag.padEnd(width)}  ${result.detail}`)

    // **Said per page, because it is per page.** Every summariser failure falls
    // back to the compiled section, which is publishable — so without this a
    // page that hit a rate limit reports `replaced` and reads as a success,
    // while sitting there in a different voice from the four around it.
    if (note) say(`    %d${note}%0`)
  }
}

/**
 * `cutver config` — what cutver actually believes, rather than what the file
 * says.
 *
 * **Every default filled in and every channel normalised**, which is the point:
 * a key that was ignored because it was misspelt is visible by its absence, and
 * a channel written `myPrefix` appears as the `my-prefix` that the version
 * string, the tag and the dist-tag will all use.
 *
 * JSON rather than YAML, because it is a format cutver also reads — the output
 * can be saved as `cutver.json` and mean exactly what it just described. Reads
 * no git and touches no network.
 */
export async function runConfig(argv: string[]): Promise<void> {
  const opts = parse(
    argv.filter(a => a !== 'config'),
    undefined,
    'config',
  )
  const root = resolveRoot(opts.cwd)
  const { config } = await loadConfig(root, opts.config).catch((e: Error) =>
    die(e.message),
  )

  // `source` is where it was read from, not something you can write back, so it
  // is reported on stderr and kept out of the document on stdout. That keeps
  // `cutver config > cutver.json` honest.
  console.error(
    `cutver: ${config.source ?? 'no config file — these are the defaults'}`,
  )
  const { source: _source, ...document } = config
  console.log(JSON.stringify(document, null, 2))
}
